### ISSUE TITLE
Support for relations with new algorithm

### ISSUE THREAD

**Issue by JosePSousa** [joto/osm-history-splitter#2]
Hello, I recently start to work with osm-history-splitter, and i must say is a very good tool to work with OSM data. My job is to split the planet pbf in the respective countries (pbf) using the poly files. I saw the features of the two algorithms "softcut" and "hardcut" and i notice that both didn't catch the nodes and ways that don't belong to the polygon region but belong to a relation that is within the region. For that reason I develop an algorithm ("softercut") to do the job, and I'm asking if you want to add this code to your tool. Unfortunately "softercut" is a three way pass.

In the attachments is a diff of the changes in the "splitter.cpp". If you agree with the idea I'll send you the algorithm.
[splitter.zip](https://github.com/joto/osm-history-splitter/files/218782/splitter.zip)

**Comment by joto** [comment]
[osmium-tool](https://github.com/osmcode/osmium-tool) has a new `extract` command which "supersedes" the OSM History Splitter. This has the "smart" strategy which keeps multipolygons together which sounds like what you wanted here.
