### ISSUE TITLE
Add a progress bar

### ISSUE THREAD

**Issue by orf** [joto/osm-history-splitter#5]
Is it possible to add some kind of progress output while running? It can be a long process, and if you're doing a softcut you cant just use "pv".

Something as simple as the total bytes read would be effective I think.

**Comment by joto** [comment]
This is difficult to do because of the file formats and the architecture of the underlying libosmium library. But I agree it would be nice to have something like this. Leaving this open, but don't expect this to be coming soon.

**Comment by joto** [comment]
[osmium-tool](https://github.com/osmcode/osmium-tool) has a new `extract` command which "supersedes" the OSM History Splitter. It has a progress bar.
