### ISSUE TITLE
make: osm-history-splitter

### ISSUE THREAD

**Issue by moll734** [joto/osm-history-splitter#6]
Hi - I am using Ubunto to run OSM-History-Splitter. Libosmium and dependencies have been added and built. All appears to run without issue until I make osm-history-splitter.

I get the following error:

mike@mike-VirtualBox:~/osm-history-splitter$ make
[ 50%] Building CXX object CMakeFiles/osm-history-splitter.dir/splitter.cpp.o
/home/mike/osm-history-splitter/splitter.cpp:9:35: fatal error: osmium/io/any_input.hpp: No such file or directory
compilation terminated.
CMakeFiles/osm-history-splitter.dir/build.make:62: recipe for target 'CMakeFiles/osm-history-splitter.dir/splitter.cpp.o' failed
make[2]: **\* [CMakeFiles/osm-history-splitter.dir/splitter.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/osm-history-splitter.dir/all' failed
make[1]: **\* [CMakeFiles/osm-history-splitter.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 

I have tried installing the old and new tool but continue to face problems. When I think that I am almost there, I get the message above.

**Comment by ImreSamu** [comment]
Hi @moll734 ,  strange ...    for me ( docker: clean  ubuntu16.04 -64bit ) this Dockerfile worked. 
https://gist.github.com/ImreSamu/e89f7287078fefcc94b6fd5ad12d322f
Can you give more info ?  ( ubuntu version, ...  )

**Comment by joto** [comment]
@moll734 It seems the includes from libosmium are not found. You have to either...
1. Install libosmium in an include path where it will be found automatically (such as /usr/include or /usr/local/include)
2. Check out libosmium and osm-history-splitter in the same directory. Then it will be found automatically.
3. Call `ccmake .` in osm-history-splitter build directory and `OSMIUM_INCLUDE_DIR` manually.
