### ISSUE TITLE
how long it takes to run a split

### ISSUE THREAD

**Issue by tongjiyiming** [joto/osm-history-splitter#7]
I am using a Ubuntu machine to run a splitter task. The machine have Intel Quad-core Exoen 3.0GHz and 16G memory. I want to get full history extract of New York City from the full history dump (53G. I use debug option to just see the process. It has run for more than 48 hours. and always have following information. Do you think it is OK? and what is the possible time to finish the task based on your experience?
![1](https://cloud.githubusercontent.com/assets/10236094/19458022/6a4f474a-9497-11e6-8150-2c2bd9028aef.JPG)

**Comment by joto** [comment]
There is something wrong there. Debug output should print massive amounts of information. It is far to much to run on anything but small tests. And the split shouldn't take that long. On the other hand 16GB is probably not enough to run this. Can you post the config file you have been using and I can give it a try.

**Comment by tongjiyiming** [comment]
This is my config:
`nyc.osm OSM nyc_bnd_175905.osm`

It seems that the boundary file I got from osm.org has no node information in it. This might be the problem.
nyc_bnd_175905.osm is a nyc boundary file I download from openstreetmap.org. The content is:
`<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="CGImap 0.5.5 (24593 thorn-02.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
 <relation id="175905" visible="true" version="38" changeset="42430720" timestamp="2016-09-25T19:51:16Z" user="miluethi" uid="19488">
  <member type="way" ref="37788405" role="outer"/>
  <member type="way" ref="37788412" role="outer"/>
  <member type="way" ref="37788493" role="outer"/>
  <member type="way" ref="37811053" role="outer"/>
  <member type="way" ref="37787073" role="outer"/>
  <member type="way" ref="37787072" role="outer"/>
  <member type="way" ref="37787122" role="outer"/>
  <member type="way" ref="37811067" role="outer"/>
  <member type="way" ref="37787976" role="outer"/>
  <member type="way" ref="37787975" role="outer"/>
  <member type="way" ref="37787971" role="outer"/>
  <member type="way" ref="37788522" role="outer"/>
  <member type="way" ref="61603751" role="outer"/>
  <member type="way" ref="309490642" role="outer"/>
  <member type="way" ref="61928627" role="outer"/>
  <member type="way" ref="61922976" role="outer"/>
  <member type="way" ref="61603744" role="outer"/>
  <member type="way" ref="61923037" role="outer"/>
  <member type="way" ref="61909165" role="outer"/>
  <member type="way" ref="37565950" role="outer"/>
  <member type="way" ref="37565866" role="outer"/>
  <member type="way" ref="37565868" role="outer"/>
  <member type="way" ref="37565564" role="outer"/>
  <member type="way" ref="37565158" role="outer"/>
  <member type="way" ref="37565053" role="outer"/>
  <member type="way" ref="37565052" role="outer"/>
  <member type="way" ref="61603753" role="outer"/>
  <member type="way" ref="37565051" role="outer"/>
  <member type="way" ref="37569166" role="outer"/>
  <member type="way" ref="61602967" role="outer"/>
  <member type="way" ref="61602968" role="outer"/>
  <member type="way" ref="61602961" role="outer"/>
  <member type="way" ref="61602969" role="outer"/>
  <member type="way" ref="61602963" role="outer"/>
  <member type="way" ref="61602964" role="outer"/>
  <member type="way" ref="61602965" role="outer"/>
  <member type="way" ref="37567463" role="outer"/>
  <member type="way" ref="37567690" role="outer"/>
  <member type="way" ref="229385899" role="outer"/>
  <member type="way" ref="189026085" role="outer"/>
  <member type="way" ref="37567199" role="outer"/>
  <member type="way" ref="37567197" role="outer"/>
  <member type="way" ref="37788575" role="outer"/>
  <member type="way" ref="120256663" role="outer"/>
  <member type="way" ref="37810234" role="outer"/>
  <member type="way" ref="37810236" role="outer"/>
  <member type="way" ref="444034108" role="outer"/>
  <member type="way" ref="37810368" role="outer"/>
  <member type="way" ref="46936809" role="outer"/>
  <member type="way" ref="444034102" role="outer"/>
  <member type="way" ref="37788309" role="outer"/>
  <member type="way" ref="37788311" role="outer"/>
  <member type="way" ref="46945175" role="outer"/>
  <member type="way" ref="37788079" role="outer"/>
  <member type="way" ref="37788080" role="outer"/>
  <member type="way" ref="37573502" role="outer"/>
  <member type="way" ref="4820654" role="outer"/>
  <member type="node" ref="61785451" role="label"/>
  <member type="way" ref="214788061" role="admin_centre"/>
  <tag k="admin_level" v="5"/>
  <tag k="alt_name" v="New York"/>
  <tag k="border_type" v="city"/>
  <tag k="boundary" v="administrative"/>
  <tag k="is_in" v="USA, New York"/>
  <tag k="is_in:country" v="USA"/>
  <tag k="is_in:country_code" v="US"/>
  <tag k="is_in:iso_3166_2" v="US-NY"/>
  <tag k="is_in:state" v="New York"/>
  <tag k="is_in:state_code" v="NY"/>
  <tag k="name" v="New York City"/>
  <tag k="name:ca" v="Nova York"/>
  <tag k="name:es" v="Nueva York"/>
  <tag k="name:ta" v="நியூ யோர்க்"/>
  <tag k="name:zh" v="纽约"/>
  <tag k="place" v="city"/>
  <tag k="short_name" v="NYC"/>
  <tag k="source" v="TIGER/Line® 2008 Place Shapefiles (http://www.census.gov/geo/www/tiger/)"/>
  <tag k="tiger:CLASSFP" v="C1"/>
  <tag k="tiger:CPI" v="Y"/>
  <tag k="tiger:FUNCSTAT" v="A"/>
  <tag k="tiger:LSAD" v="25"/>
  <tag k="tiger:MTFCC" v="G4110"/>
  <tag k="tiger:NAME" v="New York"/>
  <tag k="tiger:NAMELSAD" v="New York city"/>
  <tag k="tiger:PCICBSA" v="Y"/>
  <tag k="tiger:PCINECTA" v="N"/>
  <tag k="tiger:PLACEFP" v="51000"/>
  <tag k="tiger:PLACENS" v="02395220"/>
  <tag k="tiger:PLCIDFP" v="3651000"/>
  <tag k="tiger:STATEFP" v="36"/>
  <tag k="type" v="boundary"/>
  <tag k="wikipedia" v="en:New York City"/>
 </relation>
</osm>`

**Comment by tongjiyiming** [comment]
I use MBR  to run it. It works fine I think.
`nyc.osh.pbf BBOX -74.2591,40.4766,-73.7003,40.9177`

I believe I need to get a poly to run it.

Another question is that have you consider implement this in a distributed environment like Hadoop, or spark?

**Comment by joto** [comment]
Well, without nodes it can't work. Would be better it detected this instead of not doing anything, so I am leaving this open as a reminder to look into that.

Distributed environment: No. I am trying to do the most efficient thing that can be done with a single computer. Distributed environments are not my area of expertise.

**Comment by tongjiyiming** [comment]
OK, I have a splitted file now. Thank you!
Still, it takes about 36 hours to run on my machine. I just wonder why it takes so long. Since you can apply a bounding box to cut a small area, and process the boundary of new york city. Maybe, it is because the history dump file from osm.org don`t have an indexing structure on it? Am I right? In that case, it actually loop through all the nodes in the 53G dump file, and check if each node is in the new york city boundary.

**Comment by joto** [comment]
[osmium-tool](https://github.com/osmcode/osmium-tool) has a new `extract` command which "supersedes" the OSM History Splitter. It is much faster than the History Splitter.
